### PR TITLE
Run both builds

### PR DESCRIPTION
**Pull request by himatej**

### CODE REVIEW

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test this please

**Comment by himatej** [comment]
test

**Comment by kartheek1995** [comment]
test

**Comment by kartheek1995** [comment]
working

**Pull request closed without merging**
